### ISSUE TITLE
 Button and text sizes far too small on mobile 

### ISSUE THREAD

**Issue by nibl** [EmranAhmed/woo-variation-swatches#1]
On mobile phones, the button and text sizes are far too small. Appears to be less than half the size of text used for variation titles and drop downs. See attached screenshot. 

Tested on mobile Safari and Chrome for iOS. 
![53190700-17ea-4238-841b-12bf28ec9dc4](https://user-images.githubusercontent.com/462866/35188652-ed55aeb0-fe39-11e7-9feb-57901bd8539a.jpeg)

**Comment by EmranAhmed** [comment]
@nibl Fixed on version 1.0.7
Thank you for reporting 👍
