### ISSUE TITLE
Add image size filter

### ISSUE THREAD

**Issue by strarsis** [EmranAhmed/woo-variation-swatches#3]
Currently the image size is hard coded. It would be nice if it can be changed, ideally using a filter (from within a theme).

**Comment by EmranAhmed** [comment]
Thats a great idea, Hope I will add this feature in next version.
Thank you

**Comment by EmranAhmed** [comment]
Image size filter added and added option on admin panel.

**Comment by strarsis** [comment]
@EmranAhmed: Awesome!

**Comment by strarsis** [comment]
Is there an example for using a filter in a theme in order to change the image size?

**Comment by EmranAhmed** [comment]
Available image sizes listed on settings panel based on theme, If you want to add your own, just use `add_image_size` on `after_setup_theme` hook, or use `wvs_product_attribute_image_size` filter to change attribute image size.
