### ISSUE TITLE
IE 11 Issue

### ISSUE THREAD

**Issue by cyarema** [EmranAhmed/woo-variation-swatches#6]
I tried to hack the plugin to work with IE 11 - and once i removed this code from frontend.js: 
`jQuery(function ($) {
    Promise.resolve().then(function () {
        return __webpack_require__(11);
    }).then(function () {
        // Init on Ajax Popup :)
        $(document).on('wc_variation_form', '.variations_form', function () {
            $(this).WooVariationSwatches();
        });

        // Support for Jetpack's Infinite Scroll,
        $(document.body).on('post-load', function () {
            $('.variations_form').each(function () {
                $(this).wc_variation_form();
            });
        });
    });
}); // end of jquery main wrapper`

It worked and my other plugins then worked in IE 11, but the selection on mobile devices stopped working.  The error IE 11 is giving is 'Promise' is undefined. I am using an infinite scroll plugin as well for the shop.

I found this thread as well: https://stackoverflow.com/questions/42533264/getting-error-promise-is-undefined-in-ie11

**Comment by EmranAhmed** [comment]
IE-11 Fallback given on version: 1.0.29
