### ISSUE TITLE
Upload and use SVG images

### ISSUE THREAD

**Issue by aculine** [EmranAhmed/woo-variation-swatches#7]
Hi, is possible to use SVG images as attribute image? It could be useful. Of course SVG must be abled by functions.php, but SVG are always more used.

Thanks, Luca

**Comment by EmranAhmed** [comment]
Hello Luca ( @aculine ), 

You can try https://wordpress.org/plugins/wp-svg-images/ plugin to upload svg files. and woo-variation-swatches support svg files also.

Thanks
