### ISSUE TITLE
._delay is not defined

### ISSUE THREAD

**Issue by celsowhite** [EmranAhmed/woo-variation-swatches#8]
Hi @EmranAhmed, great plugin. In a recent update 1.0.45 I think a js function was added _.delay to woo-variation-swatches/assets/js/frontend.min.js?ver=1.0.45. I'm getting an undefined error on my product page with the update (see below.) 

I think this is because Wordpress's default underscores library v1.8.3 does not include _.delay function. Newer versions of underscores do.

<img width="1437" alt="screen shot 2018-11-01 at 3 14 34 pm" src="https://user-images.githubusercontent.com/3518732/47874036-20ab0f00-dde9-11e8-984a-ecbb92150aa3.png">

**Short Term Fix**

I switched back to version 1.0.40 of your plugin and things are working now with no console errors.

**Question**

Any thoughts on a fix for this? Should I manually include the updated underscores library rather than wordpress default?

**Comment by EmranAhmed** [comment]
Did you checked default theme and disable all plugins except Variation Swatches and WooCommerce?

underscore version 1.8.3 have delay function available.

https://github.com/jashkenas/underscore/blob/1.8.3/underscore.js#L765

Thank you

**Comment by celsowhite** [comment]
@EmranAhmed I think this issue was related to jetpack or another plugin. Strange! 

Thanks
